import { Type, type TSchema } from "@sinclair/typebox";
import {
  ApiErrorEnvelopeSchema,
  PaginationQuerySchema,
  SuccessStatusResponseSchema,
  UuidString,
} from "./common.js";
import {
  HealthLiveResponseSchema,
  HealthReadyResponseSchema,
} from "./health.js";
import {
  RegisterRequestSchema,
  RegisterResponseSchema,
  LoginRequestSchema,
  LoginResponseSchema,
  RefreshTokenRequestSchema,
  RefreshTokenResponseSchema,
  SessionListResponseSchema,
  RevokeSessionResponseSchema,
  ChangePasswordRequestSchema,
  RegenerateRecoveryCodesRequestSchema,
  RegenerateRecoveryCodesResponseSchema,
  RecoverPasswordRequestSchema,
  BffSessionExchangeRequestSchema,
  BffSessionExchangeResponseSchema,
  BffSessionRevokeRequestSchema,
} from "./auth.js";
import {
  CurrentUserResponseSchema,
  UpdateUserProfileRequestSchema,
  ExportUserDataResponseSchema,
  DeleteUserResponseSchema,
} from "./user.js";
import {
  FamilyResponseSchema,
  FamilyListResponseSchema,
  CreateFamilyRequestSchema,
  UpdateFamilyRequestSchema,
  FamilyMemberListResponseSchema,
  UpdateFamilyMemberRequestSchema,
  RemoveFamilyMemberResponseSchema,
  CreateFamilyInviteRequestSchema,
  CreateFamilyInviteResponseSchema,
  PreviewFamilyInviteQuerySchema,
  PreviewFamilyInviteResponseSchema,
  JoinFamilyRequestSchema,
  JoinFamilyResponseSchema,
  BabyResponseSchema,
  BabyListResponseSchema,
  CreateBabyRequestSchema,
  UpdateBabyRequestSchema,
  BabyMemberListResponseSchema,
  AddBabyMemberRequestSchema,
  RemoveBabyMemberResponseSchema,
} from "./family.js";
import {
  DeleteFeedingQuerySchema,
  FeedingRecordResponseSchema,
  FeedingListResponseSchema,
  CreateFeedingRequestSchema,
  UpdateFeedingRequestSchema,
  SleepRecordResponseSchema,
  SleepListResponseSchema,
  CreateSleepRequestSchema,
  UpdateSleepRequestSchema,
  DiaperRecordResponseSchema,
  DiaperListResponseSchema,
  CreateDiaperRequestSchema,
  UpdateDiaperRequestSchema,
  FoodRecordResponseSchema,
  FoodListResponseSchema,
  CreateFoodRequestSchema,
  UpdateFoodRequestSchema,
  SupplementRecordResponseSchema,
  SupplementListResponseSchema,
  CreateSupplementRequestSchema,
  UpdateSupplementRequestSchema,
  TimelineResponseSchema,
  DeleteRecordResponseSchema,
  TimelineEventSchema,
} from "./records.js";
import {
  GrowthMeasurementResponseSchema,
  GrowthMeasurementListResponseSchema,
  CreateGrowthMeasurementRequestSchema,
  UpdateGrowthMeasurementRequestSchema,
  GrowthChartResponseSchema,
  GrowthRecordSchema,
} from "./growth.js";
import {
  MedicalReportResponseSchema,
  MedicalReportListResponseSchema,
  CreateMedicalReportRequestSchema,
  UpdateMedicalReportRequestSchema,
  CreateMedicalOcrRunRequestSchema,
  MedicalOcrRunResponseSchema,
  VaccineScheduleResponseSchema,
  VaccineRecordResponseSchema,
  VaccineListResponseSchema,
  CreateVaccineRecordRequestSchema,
} from "./medical.js";
import {
  AiSessionResponseSchema,
  AiSessionListResponseSchema,
  CreateAiSessionRequestSchema,
  AiMessageListResponseSchema,
  CreateAiRunRequestSchema,
  AiRunResponseSchema,
  AiRunConfirmRequestSchema,
  AiRunConfirmResponseSchema,
  AiRunCancelResponseSchema,
  AiRunRetryResponseSchema,
  CreateVoiceRunRequestSchema,
  VoiceRunResponseSchema,
  CreateDailySummaryRunRequestSchema,
  DailySummaryRunResponseSchema,
  DailySummaryListResponseSchema,
  AiRunEventsQuerySchema,
  AiRunEventSchema,
} from "./ai.js";
import {
  SyncCommandBatchRequestSchema,
  SyncCommandBatchResponseSchema,
  FamilyChangesResponseSchema,
  UserChangesResponseSchema,
  CreateSyncSnapshotResponseSchema,
  SyncSnapshotResponseSchema,
} from "./sync.js";
import {
  CreateAttachmentRequestSchema,
  AttachmentResponseSchema,
  CompleteAttachmentRequestSchema,
  UploadUrlResponseSchema,
  DeleteAttachmentResponseSchema,
  AttachmentContentResponseSchema,
} from "./attachments.js";
import {
  RegisterPushDeviceRequestSchema,
  UnregisterPushDeviceResponseSchema,
  NotificationListResponseSchema,
  MarkNotificationReadResponseSchema,
} from "./devices.js";
import {
  FormulaProductResponseSchema,
  FormulaProductListResponseSchema,
  FormulaProductListQuerySchema,
  CreateFormulaProductRequestSchema,
  UpdateFormulaProductRequestSchema,
  FoodLibraryItemListResponseSchema,
  CreateFoodLibraryItemRequestSchema,
  FoodLibraryItemsQuerySchema,
  FoodGuidelinesResponseSchema,
  FoodPlanResponseSchema,
  SaveFoodPlanRequestSchema,
} from "./nutrition.js";
import {
  MilestoneListResponseSchema,
  ActivityListResponseSchema,
  WarningSignListResponseSchema,
  BookListResponseSchema,
  UpdateBookStatusRequestSchema,
  UpdateBookStatusResponseSchema,
} from "./knowledge.js";
import { AppConfigResponseSchema } from "./appConfig.js";
import {
  OAuthServerMetadataSchema,
  OAuthProtectedResourceMetadataSchema,
  OAuthTokenRequestSchema,
  OAuthTokenResponseSchema,
  OAuthRevokeTokenRequestSchema,
  OAuthRevokeTokenResponseSchema,
  McpRpcRequestSchema,
  McpRpcResponseSchema,
} from "./mcp.js";

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface RouteDefinition {
  method: HttpMethod;
  path: string;
  operationId: string;
  summary: string;
  tags: string[];
  implementationStatus: "READY" | "READY_TEST_SAMPLE" | "PLANNED_SH02" | "PLANNED_SH03" | "PLANNED_SH04F" | "PLANNED_SH04S" | "PLANNED_SH04D" | "PLANNED_SH04FO" | "PLANNED_SH04SU" | "PLANNED_SH04G" | "PLANNED_SH04N" | "PLANNED_SH04T" | "PLANNED_SH06" | "PLANNED_SH07" | "PLANNED_SH08" | "PLANNED_SH09";
  body?: TSchema;
  params?: TSchema;
  querystring?: TSchema;
  headers?: TSchema;
  responses: Record<number, TSchema>;
  /** Override Swagger's JSON default for responses whose wire body is not JSON. */
  responseContentTypes?: Partial<Record<number, readonly string[]>>;
}

const IdParam = Type.Object({ id: UuidString }, { additionalProperties: false });
const BabyIdParam = Type.Object({ babyId: UuidString }, { additionalProperties: false });
const BabyAndIdParam = Type.Object({ babyId: UuidString, id: UuidString }, { additionalProperties: false });
const FamilyIdParam = Type.Object({ familyId: UuidString }, { additionalProperties: false });
const FamilyAndBabyParam = Type.Object({ id: UuidString }, { additionalProperties: false });
const FamilyAndMemberParam = Type.Object({ id: UuidString, userId: UuidString }, { additionalProperties: false });
const FamilyAndProductParam = Type.Object({ familyId: UuidString, id: UuidString }, { additionalProperties: false });
const InstallationIdParam = Type.Object({ installationId: Type.String() }, { additionalProperties: false });
const ApiErrorRef = Type.Ref(ApiErrorEnvelopeSchema);

export const ROUTE_DEFINITIONS: RouteDefinition[] = [
  // 1. Health
  {
    method: "GET",
    path: "/health/live",
    operationId: "getHealthLive",
    summary: "Process liveness check",
    tags: ["Health"],
    implementationStatus: "READY",
    responses: { 200: HealthLiveResponseSchema },
  },
  {
    method: "GET",
    path: "/health/ready",
    operationId: "getHealthReady",
    summary: "Service and dependency readiness check",
    tags: ["Health"],
    implementationStatus: "READY",
    responses: { 200: HealthReadyResponseSchema },
  },

  // 2. Auth & Sessions
  {
    method: "POST",
    path: "/api/v1/auth/register",
    operationId: "register",
    summary: "Register new user account with initial session",
    tags: ["Auth"],
    implementationStatus: "PLANNED_SH03",
    body: RegisterRequestSchema,
    responses: { 201: RegisterResponseSchema, 400: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/auth/login",
    operationId: "login",
    summary: "Authenticate user and issue token pair",
    tags: ["Auth"],
    implementationStatus: "PLANNED_SH03",
    body: LoginRequestSchema,
    responses: { 200: LoginResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/auth/refresh",
    operationId: "refreshSession",
    summary: "Atomic refresh token rotation",
    tags: ["Auth"],
    implementationStatus: "PLANNED_SH03",
    body: RefreshTokenRequestSchema,
    responses: { 200: RefreshTokenResponseSchema, 401: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/auth/logout",
    operationId: "logout",
    summary: "Revoke active session and device association",
    tags: ["Auth"],
    implementationStatus: "PLANNED_SH03",
    responses: { 200: SuccessStatusResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/auth/sessions",
    operationId: "listSessions",
    summary: "List all active sessions for current user",
    tags: ["Auth"],
    implementationStatus: "PLANNED_SH03",
    responses: { 200: SessionListResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/auth/sessions/:id",
    operationId: "revokeSession",
    summary: "Revoke specific session belonging to current user",
    tags: ["Auth"],
    implementationStatus: "PLANNED_SH03",
    params: IdParam,
    responses: { 200: RevokeSessionResponseSchema, 401: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/auth/password/change",
    operationId: "changePassword",
    summary: "Change password with old password verification",
    tags: ["Auth"],
    implementationStatus: "PLANNED_SH03",
    body: ChangePasswordRequestSchema,
    responses: { 200: SuccessStatusResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/auth/recovery-codes/regenerate",
    operationId: "regenerateRecoveryCodes",
    summary: "Regenerate single-use recovery code batch",
    tags: ["Auth"],
    implementationStatus: "PLANNED_SH03",
    body: RegenerateRecoveryCodesRequestSchema,
    responses: { 200: RegenerateRecoveryCodesResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/auth/password/recover",
    operationId: "recoverPassword",
    summary: "Recover account password with single-use code",
    tags: ["Auth"],
    implementationStatus: "PLANNED_SH03",
    body: RecoverPasswordRequestSchema,
    responses: { 200: SuccessStatusResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/auth/bff/session",
    operationId: "exchangeBffSession",
    summary: "Exchange trusted Next.js BFF session secret hash for short-lived bearer token",
    tags: ["Auth"],
    implementationStatus: "PLANNED_SH03",
    body: BffSessionExchangeRequestSchema,
    responses: { 200: BffSessionExchangeResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/auth/bff/session",
    operationId: "revokeBffSession",
    summary: "Revoke Next.js BFF session by session secret hash",
    tags: ["Auth"],
    implementationStatus: "PLANNED_SH03",
    body: BffSessionRevokeRequestSchema,
    responses: { 200: SuccessStatusResponseSchema, 401: ApiErrorRef },
  },

  // 3. User & Profile
  {
    method: "GET",
    path: "/api/v1/me",
    operationId: "getCurrentUser",
    summary: "Retrieve authenticated user profile",
    tags: ["User"],
    implementationStatus: "PLANNED_SH03",
    responses: { 200: CurrentUserResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/me",
    operationId: "updateCurrentUser",
    summary: "Update current user profile attributes",
    tags: ["User"],
    implementationStatus: "PLANNED_SH03",
    body: UpdateUserProfileRequestSchema,
    responses: { 200: CurrentUserResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/me/export",
    operationId: "exportUserData",
    summary: "Queue asynchronous user data export task",
    tags: ["User"],
    implementationStatus: "PLANNED_SH03",
    responses: { 202: ExportUserDataResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/me",
    operationId: "deleteCurrentUser",
    summary: "Schedule user account deletion",
    tags: ["User"],
    implementationStatus: "PLANNED_SH03",
    responses: { 200: DeleteUserResponseSchema, 401: ApiErrorRef },
  },

  // 4. Family & Baby
  {
    method: "GET",
    path: "/api/v1/families",
    operationId: "listFamilies",
    summary: "List families accessible to current user",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    responses: { 200: FamilyListResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/families",
    operationId: "createFamily",
    summary: "Create new family with current user as admin",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    body: CreateFamilyRequestSchema,
    responses: { 201: FamilyResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/families/:id",
    operationId: "getFamily",
    summary: "Get family details by ID",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    params: IdParam,
    responses: { 200: FamilyResponseSchema, 401: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/families/:id",
    operationId: "updateFamily",
    summary: "Update family settings (admin only)",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    params: IdParam,
    body: UpdateFamilyRequestSchema,
    responses: { 200: FamilyResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/families/:id/invites",
    operationId: "createFamilyInvite",
    summary: "Generate family invitation code",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    params: IdParam,
    body: CreateFamilyInviteRequestSchema,
    responses: { 201: CreateFamilyInviteResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/families/invites/preview",
    operationId: "previewFamilyInvite",
    summary: "Public invite preview without revealing family members",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    querystring: PreviewFamilyInviteQuerySchema,
    responses: { 200: PreviewFamilyInviteResponseSchema, 404: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/families/join",
    operationId: "joinFamily",
    summary: "Join family using invite code",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    body: JoinFamilyRequestSchema,
    responses: { 200: JoinFamilyResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/families/:id/members",
    operationId: "listFamilyMembers",
    summary: "List all members in family",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    params: IdParam,
    responses: { 200: FamilyMemberListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/families/:id/members/:userId",
    operationId: "updateFamilyMember",
    summary: "Update family member role (admin only)",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    params: FamilyAndMemberParam,
    body: UpdateFamilyMemberRequestSchema,
    responses: { 200: SuccessStatusResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/families/:id/members/:userId",
    operationId: "removeFamilyMember",
    summary: "Remove member from family (or leave family)",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    params: FamilyAndMemberParam,
    responses: { 200: RemoveFamilyMemberResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/families/:id/babies",
    operationId: "listFamilyBabies",
    summary: "List babies in family",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    params: IdParam,
    responses: { 200: BabyListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/families/:id/babies",
    operationId: "createFamilyBaby",
    summary: "Create new baby profile in family",
    tags: ["Family"],
    implementationStatus: "PLANNED_SH03",
    params: IdParam,
    body: CreateBabyRequestSchema,
    responses: { 201: BabyResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:id",
    operationId: "getBaby",
    summary: "Get baby profile by ID (authorized baby members only)",
    tags: ["Baby"],
    implementationStatus: "PLANNED_SH03",
    params: IdParam,
    responses: { 200: BabyResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/babies/:id",
    operationId: "updateBaby",
    summary: "Update baby profile details",
    tags: ["Baby"],
    implementationStatus: "PLANNED_SH03",
    params: IdParam,
    body: UpdateBabyRequestSchema,
    responses: { 200: BabyResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:id/members",
    operationId: "listBabyMembers",
    summary: "List caregivers assigned to baby",
    tags: ["Baby"],
    implementationStatus: "PLANNED_SH03",
    params: IdParam,
    responses: { 200: BabyMemberListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/babies/:id/members",
    operationId: "addBabyMember",
    summary: "Add caregiver to baby",
    tags: ["Baby"],
    implementationStatus: "PLANNED_SH03",
    params: IdParam,
    body: AddBabyMemberRequestSchema,
    responses: { 201: SuccessStatusResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/babies/:id/members/:userId",
    operationId: "removeBabyMember",
    summary: "Revoke caregiver from baby (with last admin safeguard)",
    tags: ["Baby"],
    implementationStatus: "PLANNED_SH03",
    params: FamilyAndMemberParam,
    responses: { 200: RemoveBabyMemberResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },

  // 5. Care Records - Feeding (SH-04F)
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/records/feeding",
    operationId: "listFeedingRecords",
    summary: "List feeding records for a baby",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04F",
    params: BabyIdParam,
    querystring: PaginationQuerySchema,
    responses: { 200: FeedingListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/babies/:babyId/records/feeding",
    operationId: "createFeedingRecord",
    summary: "Create feeding record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04F",
    params: BabyIdParam,
    body: CreateFeedingRequestSchema,
    responses: { 201: FeedingRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/records/feeding/:id",
    operationId: "getFeedingRecord",
    summary: "Get specific feeding record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04F",
    params: BabyAndIdParam,
    responses: { 200: FeedingRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/babies/:babyId/records/feeding/:id",
    operationId: "updateFeedingRecord",
    summary: "Update feeding record with optimistic locking",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04F",
    params: BabyAndIdParam,
    body: UpdateFeedingRequestSchema,
    responses: { 200: FeedingRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/babies/:babyId/records/feeding/:id",
    operationId: "deleteFeedingRecord",
    summary: "Soft-delete feeding record with the client-observed version",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04F",
    params: BabyAndIdParam,
    querystring: DeleteFeedingQuerySchema,
    responses: { 200: DeleteRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },

  // 6. Care Records - Sleep (SH-04S)
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/records/sleep",
    operationId: "listSleepRecords",
    summary: "List sleep records for a baby",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04S",
    params: BabyIdParam,
    querystring: PaginationQuerySchema,
    responses: { 200: SleepListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/babies/:babyId/records/sleep",
    operationId: "createSleepRecord",
    summary: "Create sleep record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04S",
    params: BabyIdParam,
    body: CreateSleepRequestSchema,
    responses: { 201: SleepRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/records/sleep/:id",
    operationId: "getSleepRecord",
    summary: "Get specific sleep record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04S",
    params: BabyAndIdParam,
    responses: { 200: SleepRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/babies/:babyId/records/sleep/:id",
    operationId: "updateSleepRecord",
    summary: "Update sleep record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04S",
    params: BabyAndIdParam,
    body: UpdateSleepRequestSchema,
    responses: { 200: SleepRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/babies/:babyId/records/sleep/:id",
    operationId: "deleteSleepRecord",
    summary: "Soft-delete sleep record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04S",
    params: BabyAndIdParam,
    responses: { 200: DeleteRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },

  // 7. Care Records - Diaper (SH-04D)
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/records/diaper",
    operationId: "listDiaperRecords",
    summary: "List diaper records for a baby",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04D",
    params: BabyIdParam,
    querystring: PaginationQuerySchema,
    responses: { 200: DiaperListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/babies/:babyId/records/diaper",
    operationId: "createDiaperRecord",
    summary: "Create diaper record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04D",
    params: BabyIdParam,
    body: CreateDiaperRequestSchema,
    responses: { 201: DiaperRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/records/diaper/:id",
    operationId: "getDiaperRecord",
    summary: "Get specific diaper record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04D",
    params: BabyAndIdParam,
    responses: { 200: DiaperRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/babies/:babyId/records/diaper/:id",
    operationId: "updateDiaperRecord",
    summary: "Update diaper record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04D",
    params: BabyAndIdParam,
    body: UpdateDiaperRequestSchema,
    responses: { 200: DiaperRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/babies/:babyId/records/diaper/:id",
    operationId: "deleteDiaperRecord",
    summary: "Soft-delete diaper record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04D",
    params: BabyAndIdParam,
    responses: { 200: DeleteRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },

  // 8. Care Records - Food Logs (SH-04FO)
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/records/food",
    operationId: "listFoodRecords",
    summary: "List solid food feeding records for a baby",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04FO",
    params: BabyIdParam,
    querystring: PaginationQuerySchema,
    responses: { 200: FoodListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/babies/:babyId/records/food",
    operationId: "createFoodRecord",
    summary: "Create solid food feeding record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04FO",
    params: BabyIdParam,
    body: CreateFoodRequestSchema,
    responses: { 201: FoodRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/records/food/:id",
    operationId: "getFoodRecord",
    summary: "Get specific food feeding record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04FO",
    params: BabyAndIdParam,
    responses: { 200: FoodRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/babies/:babyId/records/food/:id",
    operationId: "updateFoodRecord",
    summary: "Update solid food feeding record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04FO",
    params: BabyAndIdParam,
    body: UpdateFoodRequestSchema,
    responses: { 200: FoodRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/babies/:babyId/records/food/:id",
    operationId: "deleteFoodRecord",
    summary: "Soft-delete solid food record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04FO",
    params: BabyAndIdParam,
    responses: { 200: DeleteRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },

  // 9. Care Records - Supplement (SH-04SU)
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/records/supplement",
    operationId: "listSupplementRecords",
    summary: "List supplement records for a baby",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04SU",
    params: BabyIdParam,
    querystring: PaginationQuerySchema,
    responses: { 200: SupplementListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/babies/:babyId/records/supplement",
    operationId: "createSupplementRecord",
    summary: "Create supplement record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04SU",
    params: BabyIdParam,
    body: CreateSupplementRequestSchema,
    responses: { 201: SupplementRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/records/supplement/:id",
    operationId: "getSupplementRecord",
    summary: "Get specific supplement record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04SU",
    params: BabyAndIdParam,
    responses: { 200: SupplementRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/babies/:babyId/records/supplement/:id",
    operationId: "updateSupplementRecord",
    summary: "Update supplement record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04SU",
    params: BabyAndIdParam,
    body: UpdateSupplementRequestSchema,
    responses: { 200: SupplementRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/babies/:babyId/records/supplement/:id",
    operationId: "deleteSupplementRecord",
    summary: "Soft-delete supplement record",
    tags: ["Records"],
    implementationStatus: "PLANNED_SH04SU",
    params: BabyAndIdParam,
    responses: { 200: DeleteRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },

  // 10. Timeline (SH-04T)
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/timeline",
    operationId: "getTimeline",
    summary: "Query unified chronological timeline for baby",
    tags: ["Timeline"],
    implementationStatus: "PLANNED_SH04T",
    params: BabyIdParam,
    querystring: PaginationQuerySchema,
    responses: { 200: TimelineResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },

  // Sample backward-compatible routes for Swift test suite verification
  {
    method: "POST",
    path: "/sample/timeline",
    operationId: "createTimelineEvent",
    summary: "Sample timeline endpoint verifying discriminated union generation in Swift",
    tags: ["Samples"],
    implementationStatus: "READY_TEST_SAMPLE",
    body: Type.Ref(TimelineEventSchema),
    responses: { 200: Type.Object({ data: Type.Ref(TimelineEventSchema) }), 400: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/sample/growth/:id",
    operationId: "getGrowthRecord",
    summary: "Sample growth endpoint verifying nullable decimal fields in Swift",
    tags: ["Samples"],
    implementationStatus: "READY_TEST_SAMPLE",
    params: IdParam,
    responses: { 200: Type.Object({ data: Type.Ref(GrowthRecordSchema) }), 404: ApiErrorRef },
  },

  // 11. Growth Measurements & Chart (SH-04G)
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/growth-measurements",
    operationId: "listGrowthMeasurements",
    summary: "List historical growth measurements for baby",
    tags: ["Growth"],
    implementationStatus: "PLANNED_SH04G",
    params: BabyIdParam,
    querystring: PaginationQuerySchema,
    responses: { 200: GrowthMeasurementListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/babies/:babyId/growth-measurements",
    operationId: "createGrowthMeasurement",
    summary: "Record new physical growth measurement",
    tags: ["Growth"],
    implementationStatus: "PLANNED_SH04G",
    params: BabyIdParam,
    body: CreateGrowthMeasurementRequestSchema,
    responses: { 201: GrowthMeasurementResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/growth-measurements/:id",
    operationId: "getGrowthMeasurement",
    summary: "Get specific growth measurement",
    tags: ["Growth"],
    implementationStatus: "PLANNED_SH04G",
    params: BabyAndIdParam,
    responses: { 200: GrowthMeasurementResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/babies/:babyId/growth-measurements/:id",
    operationId: "updateGrowthMeasurement",
    summary: "Update growth measurement with baseVersion check",
    tags: ["Growth"],
    implementationStatus: "PLANNED_SH04G",
    params: BabyAndIdParam,
    body: UpdateGrowthMeasurementRequestSchema,
    responses: { 200: GrowthMeasurementResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/babies/:babyId/growth-measurements/:id",
    operationId: "deleteGrowthMeasurement",
    summary: "Soft-delete growth measurement",
    tags: ["Growth"],
    implementationStatus: "PLANNED_SH04G",
    params: BabyAndIdParam,
    responses: { 200: DeleteRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/growth-chart",
    operationId: "getGrowthChart",
    summary: "Get growth curve points overlaid with WHO standards",
    tags: ["Growth"],
    implementationStatus: "PLANNED_SH04G",
    params: BabyIdParam,
    responses: { 200: GrowthChartResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },

  // 12. Medical & Vaccines (SH-06)
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/medical-reports",
    operationId: "listMedicalReports",
    summary: "List medical checkup and illness reports",
    tags: ["Medical"],
    implementationStatus: "PLANNED_SH06",
    params: BabyIdParam,
    querystring: PaginationQuerySchema,
    responses: { 200: MedicalReportListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/babies/:babyId/medical-reports",
    operationId: "createMedicalReport",
    summary: "Create medical checkup or lab report",
    tags: ["Medical"],
    implementationStatus: "PLANNED_SH06",
    params: BabyIdParam,
    body: CreateMedicalReportRequestSchema,
    responses: { 201: MedicalReportResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/medical-reports/:id",
    operationId: "getMedicalReport",
    summary: "Get specific medical report",
    tags: ["Medical"],
    implementationStatus: "PLANNED_SH06",
    params: BabyAndIdParam,
    responses: { 200: MedicalReportResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/babies/:babyId/medical-reports/:id",
    operationId: "updateMedicalReport",
    summary: "Update medical report details",
    tags: ["Medical"],
    implementationStatus: "PLANNED_SH06",
    params: BabyAndIdParam,
    body: UpdateMedicalReportRequestSchema,
    responses: { 200: MedicalReportResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/babies/:babyId/medical-reports/:id",
    operationId: "deleteMedicalReport",
    summary: "Soft-delete medical report",
    tags: ["Medical"],
    implementationStatus: "PLANNED_SH06",
    params: BabyAndIdParam,
    responses: { 200: DeleteRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/medical/ocr-runs",
    operationId: "createMedicalOcrRun",
    summary: "Queue OCR parsing run for uploaded medical report attachment",
    tags: ["Medical"],
    implementationStatus: "PLANNED_SH07",
    body: CreateMedicalOcrRunRequestSchema,
    responses: { 202: MedicalOcrRunResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/vaccines/schedule",
    operationId: "getVaccineSchedule",
    summary: "Get recommended national vaccine schedule",
    tags: ["Medical"],
    implementationStatus: "PLANNED_SH06",
    params: BabyIdParam,
    responses: { 200: VaccineScheduleResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/vaccines/records",
    operationId: "listVaccineRecords",
    summary: "List vaccination administration records for baby",
    tags: ["Medical"],
    implementationStatus: "PLANNED_SH06",
    params: BabyIdParam,
    responses: { 200: VaccineListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/babies/:babyId/vaccines/records",
    operationId: "createVaccineRecord",
    summary: "Record administered vaccine dose",
    tags: ["Medical"],
    implementationStatus: "PLANNED_SH06",
    params: BabyIdParam,
    body: CreateVaccineRecordRequestSchema,
    responses: { 201: VaccineRecordResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/babies/:babyId/vaccines/records/:id",
    operationId: "deleteVaccineRecord",
    summary: "Delete vaccination administration record",
    tags: ["Medical"],
    implementationStatus: "PLANNED_SH06",
    params: BabyAndIdParam,
    responses: { 200: DeleteRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },

  // 13. AI & Voice Runs (SH-07)
  {
    method: "GET",
    path: "/api/v1/ai/sessions",
    operationId: "listAiSessions",
    summary: "List private AI conversation sessions",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    querystring: PaginationQuerySchema,
    responses: { 200: AiSessionListResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/ai/sessions",
    operationId: "createAiSession",
    summary: "Create private AI session",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    body: CreateAiSessionRequestSchema,
    responses: { 201: AiSessionResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/ai/sessions/:id/messages",
    operationId: "listAiSessionMessages",
    summary: "Fetch paginated message history for AI session",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    params: IdParam,
    querystring: PaginationQuerySchema,
    responses: { 200: AiMessageListResponseSchema, 401: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/ai/sessions/:id/runs",
    operationId: "createAiRun",
    summary: "Post new message and start asynchronous AI execution run",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    params: IdParam,
    body: CreateAiRunRequestSchema,
    responses: { 202: AiRunResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 404: ApiErrorRef, 503: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/ai/runs/:id/events",
    operationId: "getAiRunEvents",
    summary: "Replay durable AI run events over a resumable SSE stream",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    params: IdParam,
    querystring: AiRunEventsQuerySchema,
    responses: { 200: AiRunEventSchema, 400: ApiErrorRef, 401: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/ai/runs/:id",
    operationId: "getAiRun",
    summary: "Get current status, progress and result of an AI run",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    params: IdParam,
    responses: { 200: AiRunResponseSchema, 401: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/ai/runs/:id/confirm",
    operationId: "confirmAiRun",
    summary: "Atomic confirmation of proposed actions from an AI run",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    params: IdParam,
    body: AiRunConfirmRequestSchema,
    responses: { 200: AiRunConfirmResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/ai/runs/:id/cancel",
    operationId: "cancelAiRun",
    summary: "Cancel active AI run without reverting already applied actions",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    params: IdParam,
    responses: { 200: AiRunCancelResponseSchema, 401: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/ai/runs/:id/retry",
    operationId: "retryAiRun",
    summary: "Retry failed AI run with a new attempt",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    params: IdParam,
    responses: { 202: AiRunRetryResponseSchema, 401: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/voice/runs",
    operationId: "createVoiceRun",
    summary: "Queue speech-to-intent and voice recording processing run",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    body: CreateVoiceRunRequestSchema,
    responses: { 202: VoiceRunResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/babies/:babyId/daily-summaries/runs",
    operationId: "createDailySummaryRun",
    summary: "Queue daily summary synthesis run for a baby and date",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    params: BabyIdParam,
    body: CreateDailySummaryRunRequestSchema,
    responses: { 202: DailySummaryRunResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/daily-summaries",
    operationId: "listDailySummaries",
    summary: "List daily summaries generated for baby",
    tags: ["AI"],
    implementationStatus: "PLANNED_SH07",
    params: BabyIdParam,
    querystring: PaginationQuerySchema,
    responses: { 200: DailySummaryListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },

  // 14. Sync Engine (SH-09)
  {
    method: "POST",
    path: "/api/v1/sync/commands",
    operationId: "executeSyncCommands",
    summary: "Execute offline mutation command batch with per-command status",
    tags: ["Sync"],
    implementationStatus: "READY",
    body: SyncCommandBatchRequestSchema,
    responses: { 200: SyncCommandBatchResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 422: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/sync/families/:familyId/changes",
    operationId: "getFamilyChanges",
    summary: "Fetch incremental change feed for family scope",
    tags: ["Sync"],
    implementationStatus: "READY",
    params: FamilyIdParam,
    querystring: PaginationQuerySchema,
    responses: { 200: FamilyChangesResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 410: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/sync/me/changes",
    operationId: "getUserChanges",
    summary: "Fetch incremental change feed for current user scope",
    tags: ["Sync"],
    implementationStatus: "READY",
    querystring: PaginationQuerySchema,
    responses: { 200: UserChangesResponseSchema, 401: ApiErrorRef, 410: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/sync/families/:id/snapshots",
    operationId: "createFamilySnapshot",
    summary: "Queue repeatable read snapshot creation for family bootstrap",
    tags: ["Sync"],
    implementationStatus: "READY",
    params: IdParam,
    responses: { 202: CreateSyncSnapshotResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/sync/families/:id/snapshots/:snapshotId",
    operationId: "getFamilySnapshot",
    summary: "Get family snapshot manifest and download status",
    tags: ["Sync"],
    implementationStatus: "READY",
    params: Type.Object({ id: UuidString, snapshotId: UuidString }, { additionalProperties: false }),
    responses: { 200: SyncSnapshotResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },

  // 15. Attachments (SH-06)
  {
    method: "GET",
    path: "/api/v1/attachments/:id/content",
    operationId: "getAttachmentContent",
    summary: "Stream an authorized attachment from private object storage",
    tags: ["Attachments"],
    implementationStatus: "PLANNED_SH06",
    params: IdParam,
    responseContentTypes: {
      200: [
        "image/jpeg",
        "image/png",
        "image/webp",
        "image/heic",
        "audio/m4a",
        "audio/wav",
        "audio/mpeg",
        "audio/mp4",
        "application/pdf",
      ],
    },
    responses: { 200: AttachmentContentResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 503: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/attachments",
    operationId: "createAttachment",
    summary: "Initialize private S3 attachment upload capability",
    tags: ["Attachments"],
    implementationStatus: "PLANNED_SH06",
    body: CreateAttachmentRequestSchema,
    responses: { 201: AttachmentResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/attachments/:id/complete",
    operationId: "completeAttachment",
    summary: "Verify size/hash and mark attachment ready",
    tags: ["Attachments"],
    implementationStatus: "PLANNED_SH06",
    params: IdParam,
    body: CompleteAttachmentRequestSchema,
    responses: { 200: SuccessStatusResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/attachments/:id/upload-url",
    operationId: "getAttachmentUploadUrl",
    summary: "Renew pre-signed upload URL for pending attachment",
    tags: ["Attachments"],
    implementationStatus: "PLANNED_SH06",
    params: IdParam,
    responses: { 200: UploadUrlResponseSchema, 401: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/attachments/:id",
    operationId: "deleteAttachment",
    summary: "Delete attachment and mark storage key for purge",
    tags: ["Attachments"],
    implementationStatus: "PLANNED_SH06",
    params: IdParam,
    responses: { 200: DeleteAttachmentResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef, 409: ApiErrorRef, 503: ApiErrorRef },
  },

  // 16. Push Devices & Notifications (SH-06)
  {
    method: "PUT",
    path: "/api/v1/devices/:installationId/push",
    operationId: "registerPushDevice",
    summary: "Register APNs/WebPush token for device installation",
    tags: ["Notifications"],
    implementationStatus: "PLANNED_SH06",
    params: InstallationIdParam,
    body: RegisterPushDeviceRequestSchema,
    responses: { 200: SuccessStatusResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/devices/:installationId/push",
    operationId: "unregisterPushDevice",
    summary: "Unregister device from push notifications",
    tags: ["Notifications"],
    implementationStatus: "PLANNED_SH06",
    params: InstallationIdParam,
    responses: { 200: UnregisterPushDeviceResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/notifications",
    operationId: "listNotifications",
    summary: "List in-app notifications for user",
    tags: ["Notifications"],
    implementationStatus: "PLANNED_SH06",
    querystring: PaginationQuerySchema,
    responses: { 200: NotificationListResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/notifications/:id/read",
    operationId: "markNotificationAsRead",
    summary: "Mark notification as read",
    tags: ["Notifications"],
    implementationStatus: "PLANNED_SH06",
    params: IdParam,
    responses: { 200: MarkNotificationReadResponseSchema, 401: ApiErrorRef, 404: ApiErrorRef },
  },

  // 17. Nutrition & Food Library (SH-04N / SH-04FO)
  {
    method: "GET",
    path: "/api/v1/families/:familyId/nutrition/products",
    operationId: "listFormulaProducts",
    summary: "List formula products configured in family",
    tags: ["Nutrition"],
    implementationStatus: "PLANNED_SH04N",
    params: FamilyIdParam,
    querystring: FormulaProductListQuerySchema,
    responses: { 200: FormulaProductListResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/families/:familyId/nutrition/products",
    operationId: "createFormulaProduct",
    summary: "Add new formula product to family catalog",
    tags: ["Nutrition"],
    implementationStatus: "PLANNED_SH04N",
    params: FamilyIdParam,
    body: CreateFormulaProductRequestSchema,
    responses: { 201: FormulaProductResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/families/:familyId/nutrition/products/:id",
    operationId: "updateFormulaProduct",
    summary: "Update formula product details or archive status",
    tags: ["Nutrition"],
    implementationStatus: "PLANNED_SH04N",
    params: FamilyAndProductParam,
    body: UpdateFormulaProductRequestSchema,
    responses: { 200: FormulaProductResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "DELETE",
    path: "/api/v1/families/:familyId/nutrition/products/:id",
    operationId: "deleteFormulaProduct",
    summary: "Soft-delete or archive formula product",
    tags: ["Nutrition"],
    implementationStatus: "PLANNED_SH04N",
    params: FamilyAndProductParam,
    responses: { 200: DeleteRecordResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef, 404: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/food/items",
    operationId: "listFoodLibraryItems",
    summary: "List common weaning and baby foods with family tried-state",
    tags: ["Nutrition"],
    implementationStatus: "PLANNED_SH04FO",
    querystring: FoodLibraryItemsQuerySchema,
    responses: { 200: FoodLibraryItemListResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/food/items",
    operationId: "createFoodLibraryItem",
    summary: "Create custom food library entry",
    tags: ["Nutrition"],
    implementationStatus: "PLANNED_SH04FO",
    body: CreateFoodLibraryItemRequestSchema,
    responses: { 201: Type.Object({ data: FoodLibraryItemListResponseSchema.properties.data.items }), 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/food/guidelines",
    operationId: "getFoodGuidelines",
    summary: "Get age-stage feeding and solid introduction guidelines",
    tags: ["Nutrition"],
    implementationStatus: "PLANNED_SH04FO",
    responses: { 200: FoodGuidelinesResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/babies/:babyId/food-plan",
    operationId: "getFoodPlan",
    summary: "Get solid food weekly/monthly plan for baby",
    tags: ["Nutrition"],
    implementationStatus: "PLANNED_SH04FO",
    params: BabyIdParam,
    responses: { 200: FoodPlanResponseSchema, 401: ApiErrorRef, 403: ApiErrorRef },
  },
  {
    method: "PUT",
    path: "/api/v1/babies/:babyId/food-plan",
    operationId: "saveFoodPlan",
    summary: "Save solid food meal plan for baby",
    tags: ["Nutrition"],
    implementationStatus: "PLANNED_SH04FO",
    params: BabyIdParam,
    body: SaveFoodPlanRequestSchema,
    responses: { 200: FoodPlanResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef, 403: ApiErrorRef, 409: ApiErrorRef },
  },

  // 18. Knowledge & Development (SH-08)
  {
    method: "GET",
    path: "/api/v1/development/milestones",
    operationId: "listMilestones",
    summary: "List developmental milestone standards by month age",
    tags: ["Knowledge"],
    implementationStatus: "PLANNED_SH08",
    responses: { 200: MilestoneListResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/development/activities",
    operationId: "listActivities",
    summary: "List recommended parent-child activities by month age",
    tags: ["Knowledge"],
    implementationStatus: "PLANNED_SH08",
    responses: { 200: ActivityListResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/development/warning-signs",
    operationId: "listWarningSigns",
    summary: "List red-flag developmental warning signs by month age",
    tags: ["Knowledge"],
    implementationStatus: "PLANNED_SH08",
    responses: { 200: WarningSignListResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "GET",
    path: "/api/v1/books",
    operationId: "listBooks",
    summary: "List parenting books with reading status",
    tags: ["Knowledge"],
    implementationStatus: "PLANNED_SH08",
    responses: { 200: BookListResponseSchema, 401: ApiErrorRef },
  },
  {
    method: "PATCH",
    path: "/api/v1/books/:id",
    operationId: "updateBookStatus",
    summary: "Update reading status for parenting book",
    tags: ["Knowledge"],
    implementationStatus: "PLANNED_SH08",
    params: Type.Object({ id: Type.String() }, { additionalProperties: false }),
    body: UpdateBookStatusRequestSchema,
    responses: { 200: UpdateBookStatusResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },

  // 19. App Config (SH-08)
  {
    method: "GET",
    path: "/api/v1/app-config",
    operationId: "getAppConfig",
    summary: "Get application runtime configuration and feature flags",
    tags: ["AppConfig"],
    implementationStatus: "PLANNED_SH08",
    responses: { 200: AppConfigResponseSchema },
  },

  // 20. OAuth 2.1 & MCP (SH-08)
  {
    method: "GET",
    path: "/.well-known/oauth-authorization-server",
    operationId: "getOAuthAuthorizationServerMetadata",
    summary: "OAuth 2.1 authorization server discovery metadata (RFC8414)",
    tags: ["OAuth"],
    implementationStatus: "PLANNED_SH08",
    responses: { 200: OAuthServerMetadataSchema },
  },
  {
    method: "GET",
    path: "/.well-known/oauth-protected-resource",
    operationId: "getOAuthProtectedResourceMetadata",
    summary: "OAuth 2.1 protected resource metadata",
    tags: ["OAuth"],
    implementationStatus: "PLANNED_SH08",
    responses: { 200: OAuthProtectedResourceMetadataSchema },
  },
  {
    method: "GET",
    path: "/.well-known/oauth-protected-resource/mcp",
    operationId: "getOAuthProtectedMcpResourceMetadata",
    summary: "OAuth 2.1 protected resource metadata for MCP endpoint",
    tags: ["OAuth"],
    implementationStatus: "PLANNED_SH08",
    responses: { 200: OAuthProtectedResourceMetadataSchema },
  },
  {
    method: "POST",
    path: "/api/v1/mcp/oauth/token",
    operationId: "exchangeMcpOAuthToken",
    summary: "Exchange authorization code or refresh token for MCP bearer token",
    tags: ["OAuth"],
    implementationStatus: "PLANNED_SH08",
    body: OAuthTokenRequestSchema,
    responses: { 200: OAuthTokenResponseSchema, 400: ApiErrorRef, 401: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/api/v1/mcp/oauth/revoke",
    operationId: "revokeMcpOAuthToken",
    summary: "Revoke MCP OAuth access or refresh token",
    tags: ["OAuth"],
    implementationStatus: "PLANNED_SH08",
    body: OAuthRevokeTokenRequestSchema,
    responses: { 200: OAuthRevokeTokenResponseSchema, 400: ApiErrorRef },
  },
  {
    method: "POST",
    path: "/mcp",
    operationId: "handleMcpRpc",
    summary: "MCP JSON-RPC 2.0 endpoint (OAuth Bearer authenticated)",
    tags: ["MCP"],
    implementationStatus: "PLANNED_SH08",
    body: McpRpcRequestSchema,
    responses: { 200: McpRpcResponseSchema, 401: ApiErrorRef },
  },
];
