-- Promote the exact 45-item Web reference catalogue into typed server-owned food rows.
-- Source: baby_panel_for_cecilia/data/04_foods.json
-- Source SHA256: 89d96cdb829f552982ddb1da76d51b85eb8d2d02a70194386e3b200cff8453d2
-- This migration changes only shared reference metadata; custom family rows and numeric nutrients_json remain intact.

ALTER TABLE public.food_library_items
  ADD COLUMN icon VARCHAR(32) NOT NULL DEFAULT '🍽️',
  ADD COLUMN food_group VARCHAR(50),
  ADD COLUMN recommended_from_month INTEGER,
  ADD COLUMN recommended_to_month INTEGER,
  ADD COLUMN exact_month_evidence BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN guidance TEXT,
  ADD COLUMN is_common_allergen BOOLEAN,
  ADD COLUMN allergen_introduction_guidance TEXT,
  ADD COLUMN high_risk_infant_needs_medical_advice BOOLEAN,
  ADD COLUMN choking_risk BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN choking_notes TEXT,
  ADD COLUMN preparation_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN avoid_before_months INTEGER,
  ADD COLUMN nutrition_highlights_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN texture_by_age_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN notes TEXT,
  ADD COLUMN source_refs_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN data_source_as_of VARCHAR(10),
  ADD COLUMN data_source_scope VARCHAR(32),
  ADD COLUMN data_source_evidence_conflict BOOLEAN,
  ADD COLUMN catalog_order INTEGER;

ALTER TABLE public.food_library_items
  ADD CONSTRAINT food_library_items_recommended_from_month_check
    CHECK (recommended_from_month IS NULL OR recommended_from_month BETWEEN 0 AND 120),
  ADD CONSTRAINT food_library_items_recommended_to_month_check
    CHECK (recommended_to_month IS NULL OR recommended_to_month BETWEEN 0 AND 120),
  ADD CONSTRAINT food_library_items_avoid_before_months_check
    CHECK (avoid_before_months IS NULL OR avoid_before_months BETWEEN 0 AND 120),
  ADD CONSTRAINT food_library_items_catalog_order_check
    CHECK (catalog_order IS NULL OR catalog_order BETWEEN 1 AND 45);

ALTER TABLE public.family_food_statuses
  ADD COLUMN first_added_date VARCHAR(10),
  ADD COLUMN acceptance INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE public.family_food_statuses
  ADD CONSTRAINT family_food_statuses_first_added_date_check
    CHECK (first_added_date IS NULL OR first_added_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
  ADD CONSTRAINT family_food_statuses_acceptance_check
    CHECK (acceptance BETWEEN 0 AND 5),
  ADD CONSTRAINT family_food_statuses_version_check
    CHECK (version >= 1);

-- Rehydrate the retained promotion fields into the active family projection.
UPDATE public.family_food_statuses
SET tried = CASE WHEN legacy_status IN ('tried','to_try') THEN legacy_status='tried' ELSE tried END,
    first_added_date = legacy_first_added_date,
    acceptance = COALESCE(legacy_acceptance, acceptance)
WHERE legacy_status IS NOT NULL OR legacy_first_added_date IS NOT NULL OR legacy_acceptance IS NOT NULL;

WITH source(catalog_order, food_id, payload) AS (
VALUES
  (1, 'food_iron_cereal', '{"id":"food_iron_cereal","name":"强化铁婴儿谷物","icon":"🥣","category":"grain","foodGroup":"grain","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"约6月龄开始辅食时，可优先选择富铁的泥糊状食物；具体品牌和添加量按产品标签及个体情况。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":["铁"],"textureByAge":[{"ageMinMonths":6,"ageMaxMonths":8,"texture":"泥糊/细腻糊状；随吞咽能力逐步增稠。"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["按说明冲调至适合吞咽的细腻质地，逐步增加稠度。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026"]}'::jsonb),
  (2, 'food_egg', '{"id":"food_egg","name":"鸡蛋","icon":"🥚","category":"protein","foodGroup":"egg","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可在开始辅食后作为多样化食物之一引入；没有可靠依据支持把蛋白统一推迟到1岁以后。"},"allergen":{"isCommonAllergen":true,"introductionGuidance":"作为常见过敏原，可在其他辅食开始时一并按一次一种新食物的方法引入并观察反应。","highRiskInfantNeedsMedicalAdvice":true},"nutrition":["蛋白质"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["充分加热至全熟；按进食能力压碎、切碎或制成软嫩质地。"],"notes":"高过敏风险婴儿如既往有严重湿疹、明确食物过敏或其他临床高风险情况，应先咨询专业人员。","sourceRefs":["src_cdc_food_intro_2026","src_nhc_feeding_2022"]}'::jsonb),
  (3, 'food_pork', '{"id":"food_pork","name":"猪肉","icon":"🥩","category":"protein","foodGroup":"meat","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"开始辅食后应逐步加入富铁动物性食物；肉类可作为铁的重要来源。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":["铁","蛋白质"],"textureByAge":[{"ageMinMonths":6,"ageMaxMonths":8,"texture":"细腻肉泥或充分研碎的肉末"},{"ageMinMonths":9,"ageMaxMonths":24,"texture":"逐步过渡为细碎、软嫩、适合咀嚼的小块"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["彻底煮熟，去骨、去筋膜和大块脂肪，按发育水平制成肉泥、肉末或软小块。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_wst678_2020","src_nhc_feeding_assessment_2025"]}'::jsonb),
  (4, 'food_beef', '{"id":"food_beef","name":"牛肉","icon":"🥩","category":"protein","foodGroup":"meat","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"开始辅食后可逐步加入富铁动物性食物。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":["铁","蛋白质"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["彻底煮熟，去筋后制成细泥/肉末，避免韧而大的肉块。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_wst678_2020","src_nhc_feeding_assessment_2025"]}'::jsonb),
  (5, 'food_chicken', '{"id":"food_chicken","name":"鸡肉","icon":"🍗","category":"protein","foodGroup":"poultry","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"开始辅食后可作为动物性食物逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":["蛋白质"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["彻底煮熟，去皮去骨，切碎或研磨至适龄质地。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_wst678_2020","src_nhc_feeding_assessment_2025"]}'::jsonb),
  (6, 'food_liver', '{"id":"food_liver","name":"动物肝脏","icon":"🫀","category":"protein","foodGroup":"organ_meat","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"国家喂养评估指南强调每天安排富铁动物性食物；动物内脏属于动物性食物来源之一。具体频次和份量本数据库不在缺乏直接依据时推算。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":["铁"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["彻底煮熟并加工为细腻、易吞咽的质地。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_wst678_2020","src_nhc_feeding_assessment_2025"]}'::jsonb),
  (7, 'food_salmon', '{"id":"food_salmon","name":"三文鱼","icon":"🐟","category":"protein","foodGroup":"fish","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"鱼类可作为动物性食物逐步引入；选择低汞鱼类更有利于控制汞暴露。"},"allergen":{"isCommonAllergen":true,"introductionGuidance":"鱼类属于常见食物过敏原之一；一次引入一种新食物并观察反应。","highRiskInfantNeedsMedicalAdvice":true},"nutrition":["蛋白质"],"textureByAge":[],"chokingRisk":true,"chokingNotes":"鱼刺可造成窒息/损伤风险；必须彻底去刺。","avoidBeforeMonths":null,"preparation":["彻底加热，仔细去除鱼刺、皮和骨，压碎成适龄质地。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_avoid_2026","src_cdc_choking_2026"]}'::jsonb),
  (8, 'food_shrimp', '{"id":"food_shrimp","name":"虾","icon":"🦐","category":"protein","foodGroup":"shellfish","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可在开始辅食后作为多样化动物性食物之一引入。"},"allergen":{"isCommonAllergen":true,"introductionGuidance":"甲壳类水产属于常见食物过敏原；按一次一种新食物方法引入并观察。","highRiskInfantNeedsMedicalAdvice":true},"nutrition":["蛋白质"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["彻底加热，去壳去硬质部分，剁碎至适龄质地。"],"notes":null,"sourceRefs":["src_cdc_food_intro_2026","src_nhc_feeding_2022"]}'::jsonb),
  (9, 'food_tofu', '{"id":"food_tofu","name":"豆腐","icon":"◻️","category":"protein","foodGroup":"legume","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"豆类/豆制品可作为食物多样性的一部分逐步引入。"},"allergen":{"isCommonAllergen":null,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":null},"nutrition":["蛋白质"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["选择新鲜、充分加热的软豆腐，压碎或切成适龄软小块。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_wst678_2020","src_nhc_feeding_assessment_2025"]}'::jsonb),
  (10, 'food_peanut_butter_thin', '{"id":"food_peanut_butter_thin","name":"稀释花生酱","icon":"🥜","category":"protein","foodGroup":"nut","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"坚果类应以不会形成硬块或黏团的安全形式提供；不能给婴幼儿整颗或碎坚果。"},"allergen":{"isCommonAllergen":true,"introductionGuidance":"花生属于常见过敏原；高风险婴儿应先咨询医疗专业人员。","highRiskInfantNeedsMedicalAdvice":true},"nutrition":["蛋白质"],"textureByAge":[],"chokingRisk":false,"chokingNotes":"大勺黏稠坚果酱以及整颗/碎坚果均是噎食风险；应稀释或薄涂。","avoidBeforeMonths":null,"preparation":["将无颗粒花生酱稀释成不黏口的薄糊，或薄薄涂在适龄软食物上。"],"notes":null,"sourceRefs":["src_cdc_food_intro_2026","src_cdc_choking_2026"]}'::jsonb),
  (11, 'food_whole_nuts', '{"id":"food_whole_nuts","name":"整颗坚果","icon":"🥜","category":"protein","foodGroup":"nut","introduction":{"recommendedFromMonth":null,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"不作为0～24月龄婴幼儿直接食用形式。"},"allergen":{"isCommonAllergen":true,"introductionGuidance":"坚果属于常见过敏原，但应以安全形态引入；整颗或碎坚果不适合婴幼儿。","highRiskInfantNeedsMedicalAdvice":true},"nutrition":["蛋白质"],"textureByAge":[],"chokingRisk":true,"chokingNotes":"整颗或碎坚果、种子为明确噎食风险。","avoidBeforeMonths":null,"preparation":["不要以整颗、碎粒或大块形式提供。"],"notes":"如需引入坚果类，改用稀释的无颗粒坚果酱等安全形态。","sourceRefs":["src_nhc_feeding_2022","src_cdc_choking_2026"]}'::jsonb),
  (12, 'food_rice_porridge', '{"id":"food_rice_porridge","name":"大米粥","icon":"🍚","category":"grain","foodGroup":"grain","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":["碳水化合物"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (13, 'food_oats', '{"id":"food_oats","name":"燕麦","icon":"🌾","category":"grain","foodGroup":"grain","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":["碳水化合物"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (14, 'food_noodles', '{"id":"food_noodles","name":"软面条","icon":"🍜","category":"grain","foodGroup":"grain","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":["碳水化合物"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (15, 'food_potato', '{"id":"food_potato","name":"土豆","icon":"🥔","category":"vegetable","foodGroup":"tuber","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":["碳水化合物"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (16, 'food_sweet_potato', '{"id":"food_sweet_potato","name":"红薯","icon":"🍠","category":"vegetable","foodGroup":"tuber","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":["碳水化合物"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (17, 'food_pumpkin', '{"id":"food_pumpkin","name":"南瓜","icon":"🎃","category":"vegetable","foodGroup":"vegetable","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (18, 'food_broccoli', '{"id":"food_broccoli","name":"西兰花","icon":"🥦","category":"vegetable","foodGroup":"vegetable","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (19, 'food_spinach', '{"id":"food_spinach","name":"菠菜","icon":"🥬","category":"vegetable","foodGroup":"vegetable","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (20, 'food_carrot', '{"id":"food_carrot","name":"胡萝卜","icon":"🥕","category":"vegetable","foodGroup":"vegetable","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":true,"chokingNotes":"生硬状态可构成噎食风险；应充分煮软或按发育水平切制。","avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (21, 'food_tomato', '{"id":"food_tomato","name":"番茄","icon":"🍅","category":"vegetable","foodGroup":"vegetable","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (22, 'food_banana', '{"id":"food_banana","name":"香蕉","icon":"🍌","category":"fruit","foodGroup":"fruit","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (23, 'food_pear', '{"id":"food_pear","name":"梨","icon":"🍐","category":"fruit","foodGroup":"fruit","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (24, 'food_apple', '{"id":"food_apple","name":"苹果","icon":"🍎","category":"fruit","foodGroup":"fruit","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":true,"chokingNotes":"生硬状态可构成噎食风险；应充分煮软或按发育水平切制。","avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (25, 'food_orange', '{"id":"food_orange","name":"橙子","icon":"🍊","category":"fruit","foodGroup":"fruit","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (26, 'food_avocado', '{"id":"food_avocado","name":"牛油果","icon":"🥑","category":"fruit","foodGroup":"fruit","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为开始辅食后的食物多样性组成部分逐步引入。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["加工至柔软、易吞咽的适龄质地；随咀嚼能力逐步从泥糊向较粗质地过渡。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026","src_cdc_texture_2026"]}'::jsonb),
  (27, 'food_grape', '{"id":"food_grape","name":"葡萄","icon":"🍇","category":"fruit","foodGroup":"fruit","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"水果可作为多样化饮食的一部分，但整颗葡萄属于明确噎食风险。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":true,"chokingNotes":"整颗葡萄是明确噎食风险。","avoidBeforeMonths":null,"preparation":["去籽并纵向切成细小、适龄的形状；进食时坐直并持续看护。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_choking_2026"]}'::jsonb),
  (28, 'food_yogurt_plain', '{"id":"food_yogurt_plain","name":"原味巴氏杀菌酸奶","icon":"🥛","category":"dairy","foodGroup":"dairy","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"可作为奶制品的一种在辅食期逐步引入；应选择巴氏杀菌、无添加糖产品。"},"allergen":{"isCommonAllergen":null,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":null},"nutrition":["蛋白质","钙"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["选择巴氏杀菌、无添加糖产品。"],"notes":null,"sourceRefs":["src_cdc_food_intro_2026","src_cdc_food_avoid_2026"]}'::jsonb),
  (29, 'food_cow_milk_drink', '{"id":"food_cow_milk_drink","name":"牛奶（作为主要饮品）","icon":"🥛","category":"dairy","foodGroup":"milk","introduction":{"recommendedFromMonth":12,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"12月龄前不应以牛奶作为主要饮品替代母乳或婴儿配方食品。"},"allergen":{"isCommonAllergen":null,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":null},"nutrition":["蛋白质","钙"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":12,"preparation":["12月龄后如提供，选择巴氏杀菌产品；具体奶类摄入结合中国指南和个体情况。"],"notes":null,"sourceRefs":["src_cdc_food_avoid_2026"]}'::jsonb),
  (30, 'food_raw_milk', '{"id":"food_raw_milk","name":"未巴氏杀菌乳/乳制品","icon":"🥛","category":"dairy","foodGroup":"milk","introduction":{"recommendedFromMonth":null,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"婴幼儿不应食用未巴氏杀菌乳或乳制品。"},"allergen":{"isCommonAllergen":null,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":null},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["不提供未巴氏杀菌乳或乳制品。"],"notes":"该禁忌不是某个精确月龄阈值，因此avoidBeforeMonths设为null。","sourceRefs":["src_cdc_food_avoid_2026"]}'::jsonb),
  (31, 'food_honey', '{"id":"food_honey","name":"蜂蜜","icon":"🍯","category":"other","foodGroup":"sweetener","introduction":{"recommendedFromMonth":12,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"12月龄前不要给蜂蜜，包括加入食物、饮水、配方奶或安抚奶嘴。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":12,"preparation":["12月龄前避免。"],"notes":null,"sourceRefs":["src_cdc_food_avoid_2026"]}'::jsonb),
  (32, 'food_added_sugar', '{"id":"food_added_sugar","name":"添加糖","icon":"🍬","category":"other","foodGroup":"sweetener","introduction":{"recommendedFromMonth":null,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"婴幼儿饮食不建议添加糖。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["选择无添加糖食物和饮品。"],"notes":"中国指南尤其强调1岁内辅食保持原味，不额外加糖；CDC对婴幼儿总体也不推荐添加糖。","sourceRefs":["src_nhc_feeding_2022","src_cdc_food_avoid_2026"]}'::jsonb),
  (33, 'food_salt_added', '{"id":"food_salt_added","name":"额外添加盐","icon":"🧂","category":"other","foodGroup":"seasoning","introduction":{"recommendedFromMonth":null,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"1岁内辅食保持原味，不额外添加盐等调味品。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["1岁内不额外加盐；1岁后也应保持清淡，具体量不在无直接来源时推算。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022"]}'::jsonb),
  (34, 'food_jelly', '{"id":"food_jelly","name":"果冻","icon":"🍮","category":"other","foodGroup":"snack","introduction":{"recommendedFromMonth":null,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"婴幼儿不推荐作为常规食物；特定形态可造成噎食风险。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":null,"highRiskInfantNeedsMedicalAdvice":false},"nutrition":[],"textureByAge":[],"chokingRisk":true,"chokingNotes":"果冻/软糖类黏滑或弹性食品可造成噎食风险。","avoidBeforeMonths":null,"preparation":["0–24月龄数据库默认不推荐提供。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022","src_cdc_choking_2026"]}'::jsonb),
  (35, 'food_high_mercury_fish', '{"id":"food_high_mercury_fish","name":"高汞鱼类","icon":"🐟","category":"protein","foodGroup":"fish","introduction":{"recommendedFromMonth":null,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"应限制/避免高汞鱼类，优先选择低汞鱼。"},"allergen":{"isCommonAllergen":true,"introductionGuidance":"鱼类可能是食物过敏原；过敏问题与汞风险是不同维度。","highRiskInfantNeedsMedicalAdvice":true},"nutrition":["蛋白质"],"textureByAge":[],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["根据权威汞风险清单选择低汞鱼；本记录不自行列出未经该来源逐项核对的中国市场鱼种。"],"notes":null,"sourceRefs":["src_cdc_food_avoid_2026"]}'::jsonb),
  (36, 'food_little_freddie_iron_rice_cereal', '{"id":"food_little_freddie_iron_rice_cereal","name":"小皮有机高铁大米粉","icon":"🥣","category":"grain","foodGroup":"grain","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":true,"guidance":"小皮经典有机大米粉，专为6月龄+初次添加辅食宝宝设计。强化富马酸亚铁（二价铁好吸收，每100g含铁约5.8mg），质地细腻顺滑好吞咽，单一大米无敏温和配方。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":"单一大米配方，极低致敏性，非常适合作为辅食第一口尝试。","highRiskInfantNeedsMedicalAdvice":false},"nutrition":["铁","碳水化合物","维生素B1"],"textureByAge":[{"ageMinMonths":6,"ageMaxMonths":7,"texture":"初次冲调建议偏稀薄如流质糊状，逐渐过渡至浓稠糊状。"},{"ageMinMonths":8,"ageMaxMonths":12,"texture":"可调得稍稠，并搭配肉泥、菜泥或辅食油一同进食。"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["取适量米粉（约5-10g）倒入宝宝小碗中","加入约60-70℃温开水或配方奶（粉水比约1:5~1:6）","静置30秒后顺时针搅拌均匀呈细腻糊状即可喂食"],"notes":"欧盟与中国双有机认证，强化二价铁好吸收。","sourceRefs":["src_nhc_feeding_2022","src_cdc_food_intro_2026"]}'::jsonb),
  (37, 'food_little_freddie_quinoa_rice_cereal', '{"id":"food_little_freddie_quinoa_rice_cereal","name":"小皮有机大米藜麦粉","icon":"🥣","category":"grain","foodGroup":"grain","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"小皮有机大米藜麦粉（6月龄+），添加全谷物有机白藜麦，富含植物蛋白、膳食纤维与必需氨基酸，强化二价铁。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":"在大米粉适应良好后引入，谷物多样化。","highRiskInfantNeedsMedicalAdvice":false},"nutrition":["铁","膳食纤维","植物蛋白","维生素B1"],"textureByAge":[{"ageMinMonths":6,"ageMaxMonths":12,"texture":"细腻泥糊状，略带天然藜麦坚果清香。"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["温开水或母乳/配方奶冲调，搅拌均匀后喂哺。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022"]}'::jsonb),
  (38, 'food_little_freddie_oatmeal_cereal', '{"id":"food_little_freddie_oatmeal_cereal","name":"小皮有机大米燕麦粉","icon":"🌾","category":"grain","foodGroup":"grain","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"小皮有机燕麦粉（6月龄+），精选优质有机燕麦，富含β-葡聚糖与水溶性膳食纤维，有助于软化便便、促进肠道舒适。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":"含有燕麦谷物，初次尝试建议少量观察。","highRiskInfantNeedsMedicalAdvice":false},"nutrition":["铁","β-葡聚糖","膳食纤维","维生素B1"],"textureByAge":[{"ageMinMonths":6,"ageMaxMonths":12,"texture":"软糯糊状，稠度随月龄调整。"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["按推荐比例冲调，易冲泡不结块。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022"]}'::jsonb),
  (39, 'food_little_freddie_prune_apple_cereal', '{"id":"food_little_freddie_prune_apple_cereal","name":"小皮有机大米西梅苹果米粉","icon":"🥣","category":"grain","foodGroup":"grain","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"小皮果蔬系列米粉（6月龄+），有机大米搭配真实西梅与苹果果粉，富含天然果胶与膳食纤维，口感酸甜清新，适合便便干燥宝宝。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":"含水果成分，初次尝试观察消化吸收。","highRiskInfantNeedsMedicalAdvice":false},"nutrition":["铁","果胶","膳食纤维","维生素C"],"textureByAge":[{"ageMinMonths":6,"ageMaxMonths":12,"texture":"细腻果香米糊。"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["温开水冲调，酸甜适口，增进食欲。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022"]}'::jsonb),
  (40, 'food_little_freddie_multigrain_blueberry_cereal', '{"id":"food_little_freddie_multigrain_blueberry_cereal","name":"小皮有机蓝莓香蕉七种谷物米粉","icon":"🥣","category":"grain","foodGroup":"grain","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"小皮7重谷物蓝莓香蕉粉（6月龄+），涵盖大米、燕麦、小麦、大麦、黑麦、玉米、小米等7种有机全谷物，搭配蓝莓香蕉果粉与二价铁。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":"含多谷物配方（含麸质谷物），建议在单一谷物耐受后再行添加。","highRiskInfantNeedsMedicalAdvice":false},"nutrition":["铁","花青素","多谷物复合膳食纤维","维生素B群"],"textureByAge":[{"ageMinMonths":7,"ageMaxMonths":18,"texture":"稠厚多谷物糊，层次丰富。"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["温开水冲调，建议7月龄及以上宝宝建立咀嚼吞咽后进食。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022"]}'::jsonb),
  (41, 'food_little_freddie_spinach_beef_cereal', '{"id":"food_little_freddie_spinach_beef_cereal","name":"小皮有机大米菠菜牛肉米粉","icon":"🥣","category":"grain","foodGroup":"grain","introduction":{"recommendedFromMonth":7,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"小皮大米菠菜牛肉粉（7月龄+），采用真实有机草饲牛肉与菠菜，荤素均衡搭配，双重铁源补充，香浓咸香口感。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":"含有牛肉成分，请确保已单独尝试过牛肉与菠菜。","highRiskInfantNeedsMedicalAdvice":false},"nutrition":["铁","优质蛋白质","叶绿素","锌","维生素A"],"textureByAge":[{"ageMinMonths":7,"ageMaxMonths":18,"texture":"浓香肉菜泥糊状。"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["温开水冲调，可作为一顿营养正餐。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022"]}'::jsonb),
  (42, 'food_little_freddie_walnut_oil', '{"id":"food_little_freddie_walnut_oil","name":"小皮特级初榨有机核桃油","icon":"🫒","category":"oil","foodGroup":"oil","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"小皮第一道冷榨有机核桃油（6月龄+），富含α-亚麻酸、亚油酸及Omega-3多不饱和脂肪酸，有助于婴幼儿大脑神经与视网膜发育。适合滴入温热的米粉、菜泥或面条中拌食。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":"精炼冷榨植物油致敏蛋白极低，初次添加先给1-2滴观察。","highRiskInfantNeedsMedicalAdvice":false},"nutrition":["α-亚麻酸(Omega-3)","亚油酸(Omega-6)","维生素E","不饱和脂肪酸"],"textureByAge":[{"ageMinMonths":6,"ageMaxMonths":12,"texture":"液体油脂，每次滴入2-5滴（约1-2ml）拌入辅食即可。"},{"ageMinMonths":12,"ageMaxMonths":36,"texture":"每次约3-5ml，拌面、拌饭或制作软辅食。"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["建议辅食出锅微温时滴入拌匀食用","不耐高温煎炸，请勿长时间高温加热","开封后避光密封保存，建议2个月内食用完"],"notes":"100%有机核桃物理冷榨，富含健脑亚麻酸。","sourceRefs":["src_nhc_feeding_2022"]}'::jsonb),
  (43, 'food_little_freddie_flaxseed_oil', '{"id":"food_little_freddie_flaxseed_oil","name":"小皮特级初榨有机亚麻籽油","icon":"🫒","category":"oil","foodGroup":"oil","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"小皮冷榨有机亚麻籽油（6月龄+），α-亚麻酸含量高达50%以上，是极佳的植物性Omega-3来源，可在体内转化为DHA/EPA，促进大脑发育与智力成长。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":"植物油无明显过敏性，适合搭配米粉或泥糊添加。","highRiskInfantNeedsMedicalAdvice":false},"nutrition":["α-亚麻酸(高达50%+)","Omega-3多不饱和脂肪酸","木酚素"],"textureByAge":[{"ageMinMonths":6,"ageMaxMonths":12,"texture":"金黄澄澈液体，滴入辅食拌食。"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["滴入米粉、蛋羹、烂面条等温热食物中拌食，请勿高温热炒。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022"]}'::jsonb),
  (44, 'food_little_freddie_avocado_oil', '{"id":"food_little_freddie_avocado_oil","name":"小皮特级初榨有机牛油果油","icon":"🥑","category":"oil","foodGroup":"oil","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"小皮特级初榨牛油果油（6月龄+），单不饱和脂肪酸（油酸）含量高，亲和肠胃好消化。烟点高（约200℃以上），既可凉拌辅食，也可用于宝宝轻煎热炒、蒸糕等多种烹饪场景。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":"天然牛油果冷榨，温和耐受性好。","highRiskInfantNeedsMedicalAdvice":false},"nutrition":["油酸(单不饱和脂肪酸)","维生素E","叶黄素","植物甾醇"],"textureByAge":[{"ageMinMonths":6,"ageMaxMonths":36,"texture":"清亮翠绿液体，口感温和清香。"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["凉拌、蒸蛋羹滴油，或轻微热炒小松饼、宝宝蔬菜肉粒均可。"],"notes":"高烟点全能辅食油，耐热耐煎炒。","sourceRefs":["src_nhc_feeding_2022"]}'::jsonb),
  (45, 'food_little_freddie_olive_oil', '{"id":"food_little_freddie_olive_oil","name":"小皮有机特级初榨热炒橄榄油","icon":"🫒","category":"oil","foodGroup":"oil","introduction":{"recommendedFromMonth":6,"recommendedToMonth":null,"exactMonthEvidence":false,"guidance":"小皮特级初榨橄榄油（6月龄+），采用地中海有机鲜果24小时内第一道物理冷榨，酸度≤0.5%，富含橄榄多酚与油酸，口感柔和不辛辣，适合辅食日常烹饪。"},"allergen":{"isCommonAllergen":false,"introductionGuidance":"单不饱和脂肪酸丰富，易吸收好代谢。","highRiskInfantNeedsMedicalAdvice":false},"nutrition":["单不饱和脂肪酸","橄榄多酚","维生素E","角鲨烯"],"textureByAge":[{"ageMinMonths":6,"ageMaxMonths":36,"texture":"清香液体油。"}],"chokingRisk":false,"chokingNotes":null,"avoidBeforeMonths":null,"preparation":["可直接滴入泥糊凉拌，也可进行低温中温热炒辅食。"],"notes":null,"sourceRefs":["src_nhc_feeding_2022"]}'::jsonb)
)
UPDATE public.food_library_items AS item
SET name = source.payload->>'name',
    icon = COALESCE(source.payload->>'icon', '🍽️'),
    category = source.payload->>'category',
    food_group = source.payload->>'foodGroup',
    recommended_from_month = NULLIF(source.payload->'introduction'->>'recommendedFromMonth', '')::INTEGER,
    recommended_to_month = NULLIF(source.payload->'introduction'->>'recommendedToMonth', '')::INTEGER,
    exact_month_evidence = COALESCE((source.payload->'introduction'->>'exactMonthEvidence')::BOOLEAN, false),
    guidance = source.payload->'introduction'->>'guidance',
    is_common_allergen = NULLIF(source.payload->'allergen'->>'isCommonAllergen', '')::BOOLEAN,
    allergen_introduction_guidance = source.payload->'allergen'->>'introductionGuidance',
    high_risk_infant_needs_medical_advice = NULLIF(source.payload->'allergen'->>'highRiskInfantNeedsMedicalAdvice', '')::BOOLEAN,
    choking_risk = COALESCE((source.payload->>'chokingRisk')::BOOLEAN, false),
    choking_notes = source.payload->>'chokingNotes',
    preparation_json = COALESCE(source.payload->'preparation', '[]'::jsonb),
    avoid_before_months = NULLIF(source.payload->>'avoidBeforeMonths', '')::INTEGER,
    nutrition_highlights_json = COALESCE(source.payload->'nutrition', '[]'::jsonb),
    texture_by_age_json = COALESCE(source.payload->'textureByAge', '[]'::jsonb),
    notes = source.payload->>'notes',
    source_refs_json = COALESCE(source.payload->'sourceRefs', '[]'::jsonb),
    data_source_as_of = '2026-08-03',
    data_source_scope = '6–24月龄',
    data_source_evidence_conflict = true,
    catalog_order = source.catalog_order
FROM source
WHERE item.id = source.food_id AND item.is_custom = false;

DO $$
DECLARE seeded_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO seeded_count FROM public.food_library_items
    WHERE is_custom=false AND data_source_as_of='2026-08-03';
  IF seeded_count <> 45 THEN
    RAISE EXCEPTION 'expected 45 promoted reference foods, got %', seeded_count;
  END IF;
END $$;
